# Generated by Django 4.2.5 on 2023-09-13 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainee',
            name='name',
        ),
    ]
